exports.seed = async function (knex) {
  await knex("bidding_entities").del();
  await knex("bidding_entities").insert([
    { name: "Prefeitura de Pelotas" },
    { name: "Prefeitura de Porto Alegre" },
    { name: "Prefeitura de Rio Grande" },
    { name: "Prefeitura de Santa Maria" },
    { name: "Prefeitura de Caxias do Sul" },
    { name: "Prefeitura de Canoas" },
    { name: "Prefeitura de Gravataí" },
    { name: "Prefeitura de Viamão" },
    { name: "Prefeitura de Novo Hamburgo" },
    { name: "Prefeitura de São Leopoldo" },
    { name: "Prefeitura de Alvorada" },
    { name: "Prefeitura de Passo Fundo" },
    { name: "Prefeitura de Sapucaia do Sul" },
    { name: "Prefeitura de Uruguaiana" },
    { name: "Prefeitura de Santa Cruz do Sul" },
    { name: "Prefeitura de Bagé" },
    { name: "Prefeitura de Bento Gonçalves" },
    { name: "Prefeitura de Erechim" },
    { name: "Prefeitura de Cachoeirinha" },
    { name: "Prefeitura de Camaquã" },
    { name: "Prefeitura de Canudos" },
    { name: "Prefeitura de Esteio" },
    { name: "Prefeitura de Ijuí" },
    { name: "Prefeitura de Lajeado" },
    { name: "Prefeitura de Morro Redondo" },
    { name: "Prefeitura de Osório" },
    { name: "Prefeitura de Palmeira das Missões" },
    { name: "Prefeitura de Salto do Jacuí" },
    { name: "Prefeitura de Santa Rosa" },
    { name: "Prefeitura de Santo Ângelo" },
    { name: "Prefeitura de São Borja" },
    { name: "Prefeitura de São Francisco de Assis" },
    { name: "Prefeitura de São José do Norte" },
    { name: "Prefeitura de São Lourenço do Sul" },
    { name: "Prefeitura de São Sepé" },
    { name: "Prefeitura de Tapes" },
    { name: "Prefeitura de Torres" },
    { name: "Prefeitura de Tramandaí" },
    { name: "Prefeitura de Três Cachoeiras" },
    { name: "Prefeitura de Três de Maio" },
    { name: "Prefeitura de Três Passos" },
    { name: "Prefeitura de Triunfo" },
    { name: "Prefeitura de Tupanciretã" },
    { name: "Prefeitura de Vacaria" },
    { name: "Prefeitura de Vera Cruz" },
    { name: "Prefeitura de Veranópolis" },
    { name: "Prefeitura de Viamão" },
    { name: "Prefeitura de Vila Flores" },
    { name: "Prefeitura de Vila Lângaro" },
  ]);
};
