exports.seed = async function (knex) {
  await knex("clients").del();
  await knex("clients").insert([
    { name: "Porto5 Investimentos Imobiliarios S.A" },
    { name: "Florestas Do Sul Agroflorestal Ltda" },
    { name: "Dom Joaquim Empreendimentos Imobiliarios Scp" },
    { name: "Nicola Comercio De Motocicletas Ltda." },
    { name: "Cmpx Participacoes E Investimentos" },
    { name: "F5 - Participacoes E Investimentos Ltda." },
    { name: "Mortagua Empreendimentos Ltda" },
    { name: "Almalagues Negocios E Participacoes Ltda" },
    { name: "Sgn Empreendimentos Imobiliarios Ltda" },
    { name: "Incorporadora E Construtora Jg Ltda" },
    { name: "Vcb Administracao De Bens E Participacoes Ltda" },
    { name: "Cooperativa Arrozeira Extremo Sul Ltda" },
    { name: "Roberto Ferreira Comercial E Construtora Ltda" },
    { name: "Bh Negocios Agropecuarios Ltda" },
    { name: "Hotel Manta" },
    { name: "Famoc Empreendimentos Imobiliarios Ltda" },
    { name: "Marcelino Administracao De Bens E Holding Familiar Ltda" },
    { name: "Empresa De Transportes Kopereck Ltda" },
    { name: "Lavagem Vitoria" },
    { name: "Diario Popular" },
    { name: "Spe Concessionaria Shopping Popular Pelotas S/A" },
    { name: "Campus Empreendimentos" },
    { name: "Kyodai" },
    { name: "Irlei Mendes Empreendimentos E Participacoes Ltda" },
    { name: "Hadler Empreendimentos E Participacoes Ltda" },
    { name: "M. Tower Empreendimentos Imobiliarios Ltda" },
    { name: "Efefe Alimentos" },
    { name: "Bertoldi S/A" },
    { name: "Valente Goulart Empreedimentos Imobiliarios Ltda Scp" },
    { name: "Pbk Empreendimentos Imobiliarios Ltda." },
    { name: "Spe Maison De Bonevalle Empreendimento Imobiliario Ltda" },
    { name: "L.M.A. Negocios E Participacoes Ltda" },
    { name: "Labore Engenharia Ltda" },
    { name: "Atacado Globo" },
    { name: "Rio Santo Resort Spe Ltda" },
    { name: "Rbk Empreendimentos Imobiliarios Ltda" },
    { name: "Arl Aluguel E Corretagem De Imoveis" },
    { name: "Radiologue" },
    { name: "Cortel Cemiterio Sao Francisco De Paula Ltda" },
    { name: "Satte Alam Veiculos E Pecas Ltda" },
    { name: "A Popular Incorporadora E Administradora De Imoveis Ltda" },
    { name: "Valente Cardoso Administracao De Imoveis Ltda" },
    { name: "Conkretus Construcoes" },
    { name: "Gobi Empreendimentos" },
    { name: "Solrac" },
    { name: "Srm Holding Ltda" },
    { name: "Jrm Empreendimentos Ltda" },
    { name: "Casas Empreendimentos" },
    { name: "Gastal Xavier E Filhos Administracoes E Participacoes Ltda." },
    { name: "Schonhofen Engenharia E Construtora" },
  ]);
};
